import {currentPerson} from '@/lib/session';
import {vacancies,applications,applicationEvents,recruiter} from '@/lib/recruitment';
import {query,ServiceIssue} from '@/lib/db';
import {WorkspaceShell} from '@/components/WorkspaceShell';
import {Hero,Panel,Empty} from '@/components/BoardView';
import {Recovery} from '@/components/Recovery';
import {ApplicationDocuments,ApplicationForm,CandidateResponse,CareerNotifications,ShareVacancy} from '@/components/RecruitmentForms';
export const dynamic='force-dynamic';
export default async function Careers({searchParams}:{searchParams:Promise<{position?:string;apply?:string}>}){try{
 const person=await currentPerson(),params=await searchParams;
 const [positions,own,events,pref]=await Promise.all([vacancies(person),person?applications(person):[],person?applicationEvents(person):[],person?query<{preferences:{career_updates?:boolean}}>('SELECT preferences FROM hub_people WHERE id=$1 AND scope=$2',[person.id,person.scope]):[]]);
 const selected=positions.find(v=>v.id===params.position),applying=positions.find(v=>v.id===params.apply),candidateApplications=person?own.filter(a=>a.person_id===person.id):[];
 const content=<><Hero title="Careers at Citizen" subtitle="Build the next chapter with us." description="Citizen Digital Ltd is recruiting for pre-licensing preparation and future operations. Employment and board appointments follow company governance and applicable regulatory assessment."/>
 {person&&recruiter(person)&&<a className="button primary" href="/recruitment">Manage recruitment</a>}<div className="dashboard-layout"><div className="primary-column">{applying&&person?<Panel title={applying.title}><ApplicationForm vacancy={applying} name={person.display_name}/></Panel>:<Panel title={selected?'Position details':'Available positions'}>{(params.position&&!selected||params.apply&&!applying)&&<p className="access-error">That position is unavailable or has closed. Choose an available position below.</p>}<div className="opportunity-grid">{(selected?[selected]:positions.filter(v=>v.status==='open'&&new Date(v.closes_at)>new Date())).map(v=><article key={v.id} className="opportunity-card"><span className="chip">{v.kind==='board'?'Board appointment':'Employment'}</span><h2>{v.title}</h2><p>{v.summary}</p><p>{v.location} · {v.phase.replaceAll('_',' ')}</p><p><strong>Closes:</strong> {new Date(v.closes_at).toLocaleString('en-ZA',{timeZone:'Africa/Johannesburg'})} SAST</p><p className="application-statement">{v.requirements}</p><a href={v.source_link} target="_blank" rel="noopener noreferrer">Read source advertisement ↗</a>{candidateApplications.some(a=>a.vacancy_id===v.id)?<a className="button primary" href="#applications">View my application</a>:<a className="button primary" href={person?'/careers?apply='+v.id:'/login?next='+encodeURIComponent('/careers?apply='+v.id)}>Apply for this position</a>}<ShareVacancy id={v.id}/></article>)}</div>{!positions.length&&<Empty>No positions are currently open. Return later for new opportunities.</Empty>}{selected&&<a className="button" href="/careers">All positions</a>}</Panel>}
 {person&&<section id="applications"><Panel title="My applications">{!candidateApplications.length?<Empty>You have not submitted an application yet.</Empty>:candidateApplications.map(a=><article className="finding-row" key={a.id}><h3>{a.title}</h3><span className="chip">{a.status.replaceAll('_',' ')}</span><p>{a.candidate_note||'Application received. Awaiting review.'}</p><a href={a.cv_link} target="_blank" rel="noopener noreferrer">My CV ↗</a>{['submitted','under_review','shortlisted','interview','checks'].includes(a.status)&&<ApplicationDocuments application={a}/>}{a.offer_link&&<a className="button" href={a.offer_link} target="_blank" rel="noopener noreferrer">Review offer ↗</a>}{a.status==='offered'&&<div className="actions"><CandidateResponse application={a} status="accepted" label="Accept offer"/><CandidateResponse application={a} status="declined" label="Decline offer"/></div>}{!['employed','appointed','rejected','withdrawn','declined'].includes(a.status)&&<CandidateResponse application={a} status="withdrawn" label="Withdraw application"/>}<details><summary>Application timeline</summary>{events.filter(e=>e.application_id===a.id).map((e,i)=><p key={i}><strong>{e.status.replaceAll('_',' ')}</strong> · {new Date(e.created_at).toLocaleDateString('en-ZA')}<br/>{e.note}</p>)}</details></article>)}</Panel></section>}</div>
 <aside className="context-column"><Panel title="Your profile, reused">{person?<><p>Applying as {person.display_name}</p><a className="button" href="/profile">Check contact details</a></>:<><p>Use one Citizen identity for investments, banking and career applications.</p><a className="button" href="/register?next=/careers">Create an account</a><a className="button" href="/login?next=/careers">Sign in</a></>}<p className="muted">Applications and documents are private to you and authorised administrators. Holding shares does not guarantee an appointment.</p></Panel>{person&&<Panel title="Career updates"><CareerNotifications initial={pref[0]?.preferences?.career_updates!==false}/></Panel>}<Panel title="Document access"><p className="muted">CVs, references and offer documents remain in Google Drive. Use restricted shared links and grant access to the intended reviewers. Direct upload is pending the server Drive connection.</p></Panel><Panel title="Need guidance?"><a className="button" href="/ai">Ask CitizenAI</a><p className="muted">The assistant explains the process; authorised people make recruitment decisions.</p></Panel></aside></div></>;
 return person?<WorkspaceShell person={person} active="careers">{content}</WorkspaceShell>:<main id="main" className="public-opportunities"><a className="button" href={process.env.NEXT_PUBLIC_WEBSITE_URL}>← Citizen Bank website</a>{content}</main>;
 }catch(e){if(e instanceof ServiceIssue)return <Recovery code={e.code} message={e.message}/>;throw e;}}
