import {currentPerson} from '@/lib/session';
import {can} from '@/lib/contracts';
import {query,ServiceIssue} from '@/lib/db';
import {WorkspaceShell} from '@/components/WorkspaceShell';
import {Hero,Panel,Empty} from '@/components/BoardView';
import {Recovery} from '@/components/Recovery';
import {ActionButton} from '@/components/ActionButton';
import {InvestorQuestion} from '@/components/InvestorQuestion';
import {DataRoomAccess} from '@/components/DataRoomAccess';
export const dynamic='force-dynamic';
type Document={id:string;title:string;category:string;summary:string;shared_link:string;stage:number;document_status:string;publication:string};
type Question={id:string;question:string;answer:string|null;display_name:string;created_at:string};
export default async function DataRoom(){try{
 const person=await currentPerson();const admin=!!person&&can(person.roles,['admin']);
 const [documents,questions]=person?await Promise.all([
 query<Document>(`SELECT * FROM hub_data_room_documents d WHERE scope=$1 AND ($2::boolean OR (publication='released' AND (stage=1 OR EXISTS(SELECT 1 FROM hub_data_room_access a WHERE a.person_id=$3 AND a.stage=d.stage)))) ORDER BY stage,category,title`,[person.scope,admin,person.id]),
 query<Question>(`SELECT q.*,p.display_name FROM hub_investor_questions q JOIN hub_people p ON p.id=q.person_id WHERE q.scope=$1 AND ($2::boolean OR q.person_id=$3) ORDER BY q.created_at DESC LIMIT 100`,[person.scope,admin,person.id])
 ]):[[],[]];
 const content=<><Hero title="Investor data room" subtitle="Understand the opportunity before you invest." kind="investor" description="Company records, investment terms, licensing evidence and working plans remain in Google Drive. Each document’s status is visible; drafts and forecasts are not completed approvals."/><div className="dashboard-layout"><div className="primary-column"><Panel title="Your investment evidence">{!person?<><p>Sign in or create a Citizen investor account to review released documents and ask questions.</p><a className="button primary" href="/register">Create investor account</a><a className="button" href="/login?next=/dataroom">Sign in</a></>:documents.length?<div className="readiness-items">{documents.map(d=><article className="finding-row" key={d.id}><span className="chip">{d.category} · Stage {d.stage}</span><h3>{d.title}</h3><p>{d.summary}</p><p className="muted">{d.document_status.replaceAll('_',' ')}{admin?' · '+d.publication:''}</p><a className="button" href={d.shared_link} target="_blank" rel="noopener noreferrer">View in Google Drive ↗</a>{admin&&<ActionButton label={d.publication==='released'?'Withdraw from investor view':'Release to permitted investors'} path="/api/dataroom" payload={{action:'publish',id:d.id,publication:d.publication==='released'?'withdrawn':'released'}}/>}</article>)}</div>:<Empty>No documents have been released for your current access stage yet.</Empty>}</Panel>{person&&<Panel title={admin?'Investor questions and responses':'Your questions and responses'}>{!admin&&<InvestorQuestion/>}{questions.map(q=><article className="finding-row" key={q.id}>{admin&&<small>{q.display_name}</small>}<h3>{q.question}</h3>{q.answer?<p>{q.answer}</p>:<p className="muted">Awaiting an administrator response.</p>}{admin&&<InvestorQuestion id={q.id} answer/>}</article>)}</Panel>}</div><aside className="context-column"><Panel title="Access by investment stage"><ol><li>Introduction, current subscription terms and company overview.</li><li>Business case and financial planning after NDA.</li><li>Due diligence after KYC and source-of-funds clearance.</li><li>Term sheet after approval of the proposed structure.</li><li>Definitive agreements and closing after required approvals.</li></ol><p>Google Drive may ask you to request Viewer access using your registered email. Draft status and access requirements remain visible.</p><a className="button" href="/opportunities">View subscription opportunities</a></Panel>{admin&&<Panel title="Grant investor stage access"><DataRoomAccess/></Panel>}<Panel title="Investment enquiries"><a href="mailto:investors@citizenbank.co.ls">investors@citizenbank.co.ls</a><p>Personal identity documents, other investors’ contracts and internal board deliberations are not part of the general investor data room.</p></Panel></aside></div></>;
 return person?<WorkspaceShell person={person} active="investors">{content}</WorkspaceShell>:<main className="public-opportunities" id="main"><a className="button" href={process.env.NEXT_PUBLIC_WEBSITE_URL}>← Citizen Bank website</a>{content}</main>;
 }catch(e){if(e instanceof ServiceIssue)return <Recovery code={e.code} message={e.message}/>;throw e;}}
