"use client";
import { useEffect,useRef,useState } from "react";
import { accountCatalog } from "@/lib/contracts";
export function AccountForm({enabled,next="/",account,service}:{enabled:boolean;next?:string;account?:string;service?:string}){
 const [show,setShow]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const started=useRef(false);const previous=useRef<Record<string,string>|null>(null);
 async function signin(payload:Record<string,string>){previous.current=payload;setBusy(payload.account||'normal');setError(null);try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,next,...(service==='banking'||service==='app'?{service}:{})})});const data=await response.json();if(!response.ok)throw new Error(`${data.error} (${data.code})`);window.location.assign(data.next);}catch(e){setError(e instanceof Error?e.message:"Sign-in could not be completed. Please retry.");setBusy(null);}}
 useEffect(()=>{if(enabled&&accountCatalog.some(item=>item.key===account)&&!started.current){started.current=true;void signin({account:account!});}},[account,enabled]);
 return <div className="access-card"><img src="/brand/logo.webp" alt="Citizen Bank"/><span className="eyebrow">ONE CITIZEN. MANY POSSIBILITIES.</span><h1>Welcome to Citizen Hub</h1><p>Your board, investment and institutional workspace.</p>
 <form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void signin({email:String(data.get('email')),password:String(data.get('password'))});}}><label>Email address<input required type="email" autoComplete="username" name="email" placeholder="you@example.com"/></label><label>Password<input required type="password" autoComplete="current-password" name="password"/></label><button className="button primary full" disabled={!!busy}>{busy==='normal'?'Signing in…':'Sign in to your account'}</button></form>
 {error&&<div role="alert" className="form-error"><strong>Sign-in needs attention</strong><p>{error}</p><button className="button" onClick={()=>previous.current&&void signin(previous.current)}>Retry</button><button className="button" onClick={()=>history.back()}>Go back</button><button className="button" onClick={()=>setError(null)}>Cancel</button></div>}
 {enabled&&<section className="access-demonstration"><button className="button full" onClick={()=>setShow(!show)} aria-expanded={show}>Try the demonstration {show?'−':'+'}</button>{show&&<><p>Choose a fictional account. No real money moves.</p><div className="account-grid">{accountCatalog.map(item=><button disabled={!!busy} key={item.key} onClick={()=>void signin({account:item.key})}><strong>{busy===item.key?'Signing in…':item.key}</strong><small>{item.description}</small></button>)}</div></>}</section>}
 <a className="access-return" href={process.env.NEXT_PUBLIC_WEBSITE_URL}>← Back to Citizen Bank website</a></div>;
}
