"use client";
import { useState } from "react";
import {recoveryActions} from '@/lib/recovery-policy';
export function ActionButton({label,path,payload,className="button"}:{label:string;path:string;payload:Record<string,unknown>;className?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[done,setDone]=useState(false),[code,setCode]=useState('REQUEST_FAILED');
 async function run(){setBusy(true);setError(null);setCode('REQUEST_FAILED');try{const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(20000)});const data=await response.json().catch(()=>({}));if(!response.ok){setCode(data.code||'REQUEST_FAILED');throw new Error(`${data.error||'The request failed.'} (${data.code||response.status})`);}setDone(true);}catch(e){setError(e instanceof Error?e.message:"This action failed. Check the latest record before retrying.");}finally{setBusy(false);}}
 const action=recoveryActions(code)[0];
 return <span className="action-wrapper"><button className={className} type="button" onClick={run} disabled={busy||done}>{done?"Saved":busy?"Saving…":label}</button>{done&&<button className="button" type="button" onClick={()=>window.location.reload()}>View updated record</button>}{error&&<span className="inline-error" role="alert">{error}{action==='retry'?<button type="button" disabled={busy} onClick={run}>Retry</button>:action==='reload'?<button type="button" onClick={()=>window.location.reload()}>Reload latest record</button>:<a href={action==='opportunities'?'/opportunities':action==='sign_in'?'/login':'/'}>{action==='opportunities'?'View opportunities':action==='sign_in'?'Sign in again':'My workspace'}</a>}<button type="button" onClick={()=>setError(null)}>Cancel</button></span>}</span>;
}
