
import {Countdown} from "./Countdown";
import { Icon } from "./Icon";
import { ActionButton } from "./ActionButton";
import type { Person } from "@/lib/contracts";
import { money,type Overview,type Task } from "@/lib/data";
const date=(value:string)=>new Intl.DateTimeFormat("en-ZA",{day:"numeric",month:"short",year:"numeric",timeZone:"Africa/Johannesburg"}).format(new Date(value));
export function Panel({title,link,children,className=""}:{title:string;link?:string;children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-heading"><h2>{title}</h2>{link&&<a href={link}>View all ↗</a>}</div>{children}</section>;}
export function Empty({children}:{children:React.ReactNode}){return <p className="empty-state">{children}</p>;}
export function Tasks({tasks}:{tasks:Task[]}){return <div className="activity-list">{tasks.filter(t=>t.status==='open').length?tasks.filter(t=>t.status==='open').map((task,index)=><div className="activity-row" key={task.id}><span className={`tone-icon tone-${index%4}`}><Icon name="file"/></span><div><strong>{task.title}</strong><small>{task.due_at?`Due ${date(task.due_at)}`:"No deadline"}</small></div><span className={`chip ${task.priority==='high'?'danger':''}`}>{task.priority}</span><ActionButton label="Complete" path="/api/workspace" payload={{action:'complete_task',id:task.id}}/></div>):<Empty>You are all caught up.</Empty>}</div>;}
export function Events({data}:{data:Overview}){return <div className="events-list">{data.meetings.filter(m=>m.status==='scheduled').slice(0,4).map(meeting=><a href={`/board?meeting=${meeting.id}`} className="event-row" key={meeting.id}><span className="date-tile"><strong>{new Date(meeting.starts_at).getDate().toString().padStart(2,'0')}</strong><small>{new Date(meeting.starts_at).toLocaleString('en-ZA',{month:'short'})}</small></span><span><strong>{meeting.title}</strong><small>{meeting.committee} · {new Date(meeting.starts_at).toLocaleTimeString('en-ZA',{hour:'2-digit',minute:'2-digit',timeZone:'Africa/Johannesburg'})}</small></span><Icon name="calendar" size={17}/></a>)}{!data.meetings.length&&<Empty>No meetings scheduled.</Empty>}</div>;}
export function Documents({data}:{data:Overview}){return <div className="document-list">{data.documents.slice(0,4).map(doc=><a key={doc.id} href={doc.shared_link} target="_blank" rel="noopener noreferrer" className="document-row"><span className="document-icon"><Icon name="file"/></span><span><strong>{doc.name}</strong><small>Google Drive · Version {doc.version} · {date(doc.updated_at)}</small></span><span>↗</span></a>)}{!data.documents.length&&<Empty>No Google Drive documents have been shared with this account.</Empty>}</div>;}
export function Metrics({items}:{items:{icon:string;label:string;value:string;detail:string}[]}){return <div className="kpi-strip">{items.map((item,index)=><div className="kpi-card" key={item.label}><span className={`tone-icon tone-${index%4}`}><Icon name={item.icon} size={26}/></span><div><small>{item.label}</small><strong>{item.value}</strong><span>{item.detail}</span></div></div>)}</div>;}
export function Hero({title,subtitle,kind="board",description}:{title:string;subtitle:string;kind?:string;description?:string}){return <section className={`hero hero-${kind}`}><div className="hero-copy"><h1>{title}</h1><p>{subtitle}</p>{description&&<small>{description}</small>}</div><div className="hero-art" aria-hidden/><blockquote>“Strong governance today,<br/>a stronger Africa tomorrow.”</blockquote></section>;}
export function BoardView({person,data}:{person:Person;data:Overview}){
 const next=data.meetings.find(meeting=>meeting.status==='scheduled'&&new Date(meeting.starts_at)>new Date());
 return <><Hero title="Board Portal" subtitle="Governance. Oversight. Strategic Direction." description="Access board information, meetings, documents, resolutions and key actions."/>
 <div className="dashboard-layout"><div className="primary-column"><Metrics items={[
 {icon:'calendar',label:'Upcoming meeting',value:next?date(next.starts_at):'Not scheduled',detail:next?.committee||'Your board calendar'},
 {icon:'file',label:'Pending resolutions',value:String(data.resolutions.filter(r=>r.status==='open').length),detail:'Require your attention'},
 {icon:'check',label:'Open actions',value:String(data.tasks.filter(t=>t.status==='open').length),detail:'Assigned to your account'},
 {icon:'documents',label:'Documents',value:String(data.documents.length),detail:'Shared Google Drive records'},
 ]}/>
 <div className="content-grid"><Panel title="Next Board Meeting" className="meeting-feature">{next?<><span className="chip purple">{next.committee}</span><h3>{next.title}</h3><p>{date(next.starts_at)} · {next.location}</p><div className="button-row"><a className="button primary" href="#agenda">View agenda</a><ActionButton label="Accept invitation" path="/api/workspace" payload={{action:'rsvp',id:next.id,response:'accepted'}}/></div></>:<Empty>Your next meeting will appear here once scheduled.</Empty>}</Panel>
 <Panel title="Meeting Countdown"><Countdown startsAt={next?.starts_at||null}/></Panel>
 <Panel title="Board Members"><div className="member-grid">{data.members.map(member=><article className="member-card" key={member.id}><span className="member-avatar">{member.display_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><strong>{member.display_name}</strong><small>Board member</small>{member.id===person.id&&<span className="chip purple">You</span>}<span className="chip success">Active</span></article>)}</div>{!data.members.length&&<Empty>No board members recorded.</Empty>}</Panel><Panel title="Board Committees"><div className="committee-list">{['Audit Committee','Risk Committee','Remuneration Committee','Nominations Committee','Strategy Committee'].map((name,index)=><div className="committee-row" key={name}><span className={`tone-icon tone-${index%4}`}><Icon name={index===1?'risk':'board'}/></span><div><strong>{name}</strong><small>Coming soon · Committee management</small></div></div>)}</div></Panel>
 <Panel title="Meeting agenda" className="span-2"><div id="agenda">{next?.agenda.length?next.agenda.map((item,index)=><div className="agenda-row" key={index}><span>{String(index+1).padStart(2,'0')}</span><strong>{item.title}</strong><small>{item.duration} minutes</small></div>):<Empty>No agenda published yet.</Empty>}</div></Panel>
 <Panel title="Key Documents" link="/documents"><Documents data={data}/></Panel><Panel title="Board Actions"><Tasks tasks={data.tasks}/></Panel>
 </div></div><aside className="context-column"><Panel title="Upcoming Meetings"><Events data={data}/></Panel><Panel title="Recent Resolutions">{data.resolutions.length?data.resolutions.map(resolution=><div className="resolution-row" key={resolution.id}><span className={`status-dot ${resolution.status==='approved'?'success':'warn'}`}/><div><strong>{resolution.title}</strong><small>Closes {date(resolution.closes_at)}</small><p>{resolution.description}</p>{resolution.status==='open'&&person.roles.includes('board_member')&&<div className="button-row"><ActionButton label={resolution.choice==='for'?'Voted for':'Vote for'} path="/api/workspace" payload={{action:'vote',id:resolution.id,choice:'for'}}/><ActionButton label="Vote against" path="/api/workspace" payload={{action:'vote',id:resolution.id,choice:'against'}}/><ActionButton label="Abstain" path="/api/workspace" payload={{action:'vote',id:resolution.id,choice:'abstain'}}/></div>}</div><span className="chip">{resolution.status}</span></div>):<Empty>No resolutions published.</Empty>}</Panel><QuickActions/></aside></div></>;
}
export function QuickActions(){return <Panel title="Quick Actions"><div className="quick-grid">{[{label:'Board calendar',icon:'calendar',href:'/board'},{label:'Link document',icon:'file',href:'/documents'},{label:'Investor portal',icon:'investors',href:'/investors'},{label:'My profile',icon:'profile',href:'/profile'},{label:'Communications',icon:'communications',href:'/communications'},{label:'Ask Citizen AI',icon:'ai',href:'/ai'}].map((action,index)=><a className={`quick-action tone-${index%4}`} key={action.label} href={action.href}><Icon name={action.icon} size={26}/><span>{action.label}</span></a>)}</div></Panel>;}
export function ExecutiveView({person,data}:{person:Person;data:Overview}){const amount=Number(data.capital.received),progress=Math.min(100,amount/25000000*100);return <><Hero title={`Welcome, ${person.display_name.split(' ')[0]}`} subtitle="Here’s your institutional overview." kind="executive"/><div className="dashboard-layout"><div className="primary-column"><Metrics items={[{icon:'finance',label:'Capital received',value:money(amount),detail:'Recorded institutional receipts'},{icon:'licensing',label:'Business stage',value:'Pre-licensing',detail:'Application and preparation'},{icon:'investors',label:'Investor relationships',value:data.capital.investors,detail:'Active recorded commitments'},{icon:'check',label:'Outstanding actions',value:String(data.tasks.filter(t=>t.status==='open').length),detail:'Require your attention'}]}/><div className="content-grid"><Panel title="Regulatory Licensing Progress"><div className="milestone-track"><span >Preparation</span><span>Application</span><span>Review</span><span>Approval</span></div><div className="notice"><Icon name="licensing"/><div><strong>Pre-licensing institutional workspace</strong><p>Track preparation without implying regulatory approval. The detailed licensing workflow is coming soon.</p></div><a className="button primary" href="/licensing">View requirements</a></div></Panel><Panel title="Capital Raising Progress"><div className="capital-display"><div className="donut" style={{'--progress':`${progress}%`} as React.CSSProperties}><span><strong>{Math.round(progress)}%</strong><small>{money(amount)}</small></span></div><div><p><i className="legend-dot"/>Received<br/><strong>{money(amount)}</strong></p><p>Committed<br/><strong>{money(data.capital.committed)}</strong></p><small>Planning target {money(25000000)}</small></div></div></Panel><Panel title="Institutional Priorities" className="span-2"><div className="priority-grid">{[{name:'Governance',href:'/board',icon:'board'},{name:'Investor relations',href:'/investors',icon:'investors'},{name:'Documents & knowledge',href:'/documents',icon:'documents'},{name:'People & careers',href:'/people',icon:'people'}].map(item=><a href={item.href} className="priority-card" key={item.name}><Icon name={item.icon} size={28}/><strong>{item.name}</strong><small>Open workspace ↗</small></a>)}</div></Panel><Panel title="Recent Activity" link="/communications">{data.notifications.slice(0,3).map(n=><div className="activity-row" key={n.id}><span className="tone-icon tone-0"><Icon name="activity"/></span><div><strong>{n.title}</strong><small>{n.body}</small></div></div>)}{!data.notifications.length&&<Empty>No recent activity.</Empty>}</Panel><Panel title="Knowledge & Evidence" link="/documents"><Documents data={data}/></Panel></div></div><aside className="context-column"><Panel title="My Tasks"><Tasks tasks={data.tasks}/></Panel><Panel title="Upcoming Events"><Events data={data}/></Panel><QuickActions/></aside></div></>;}
