"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Send,Volume2,Square,Settings2,Sparkles} from 'lucide-react';
import type {AIPreferences} from '@/lib/citizen-ai';
type Message={role:'user'|'assistant';content:string};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;start:()=>void;stop:()=>void;onresult:((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null};
type SpeechWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export function CitizenAI({initial}:{initial:AIPreferences}){
 const [prefs,setPrefs]=useState(initial),[settings,setSettings]=useState(false),[messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<{message:string;code:string}|null>(null),[status,setStatus]=useState<{chat:boolean;speech:boolean}|null>(null),[listening,setListening]=useState(false),[speaking,setSpeaking]=useState(false),[saved,setSaved]=useState('');
 const pending=useRef<AbortController|null>(null),audio=useRef<HTMLAudioElement|null>(null),audioURL=useRef<string|null>(null),recognition=useRef<Recognition|null>(null),end=useRef<HTMLDivElement|null>(null),speechPending=useRef<AbortController|null>(null);
 function stopSpeech(){speechPending.current?.abort();audio.current?.pause();audio.current=null;if(audioURL.current)URL.revokeObjectURL(audioURL.current);audioURL.current=null;window.speechSynthesis?.cancel();setSpeaking(false);}
 useEffect(()=>{const controller=new AbortController();fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'status'}),signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Object.assign(Error(d.error),{code:d.code});setStatus(d);}).catch(e=>{if(e.name!=='AbortError')setError({message:e.message||'CitizenAI status could not be checked.',code:e.code||'AI_CONNECTION_INTERRUPTED'});});return()=>{controller.abort();pending.current?.abort();speechPending.current?.abort();recognition.current?.stop();audio.current?.pause();if(audioURL.current)URL.revokeObjectURL(audioURL.current);window.speechSynthesis?.cancel();};},[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages,busy]);
 async function savePreferences(){setSaved('');try{const r=await fetch('/api/ai/preferences',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(prefs),signal:AbortSignal.timeout(12000)}),d=await r.json();if(!r.ok)throw Error(d.error);setSaved('Preferences saved to your Citizen Hub profile.');}catch(e){setError({message:e instanceof Error?e.message:'Preferences could not be saved. Retry.',code:'PREFERENCES_UNAVAILABLE'});}}
 async function speak(text:string){stopSpeech();setSpeaking(true);const controller=new AbortController();speechPending.current=controller;try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'speech',text:text.slice(0,4000),language:prefs.language}),signal:controller.signal});if(!r.ok)throw Error('Cloud speech is unavailable.');const blob=await r.blob();if(controller.signal.aborted)return;audioURL.current=URL.createObjectURL(blob);const player=new Audio(audioURL.current);audio.current=player;player.onended=stopSpeech;player.onerror=()=>{stopSpeech();setError({message:'Audio could not be played. The reply remains on screen.',code:'VOICE_UNAVAILABLE'});};await player.play();}catch(e){if(controller.signal.aborted)return;if(window.speechSynthesis){const utterance=new SpeechSynthesisUtterance(text);utterance.lang={en:'en-ZA',st:'st-LS',zu:'zu-ZA'}[prefs.language];const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith(prefs.language));if(prefs.language!=='en'&&!voice){setSpeaking(false);setError({message:'Cloud speech is unavailable and this device has no voice for the selected language. Read the reply or choose English.',code:'VOICE_UNAVAILABLE'});return;}if(voice)utterance.voice=voice;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>{setSpeaking(false);setError({message:'This device could not read the reply aloud. The text remains available.',code:'VOICE_UNAVAILABLE'});};window.speechSynthesis.speak(utterance);setSaved('Using this device’s speech voice because cloud speech is unavailable.');}else{setSpeaking(false);setError({message:'Speech is unavailable on this device. The reply remains on screen.',code:'VOICE_UNAVAILABLE'});}}}
 function dictate(){if(listening){recognition.current?.stop();return;}const Constructor=(window as SpeechWindow).SpeechRecognition||(window as SpeechWindow).webkitSpeechRecognition;if(!Constructor){setError({message:'Voice input is not supported by this browser. Type your question below.',code:'VOICE_INPUT_UNAVAILABLE'});return;}const r=new Constructor();recognition.current=r;r.lang=prefs.language==='zu'?'zu-ZA':'en-ZA';r.continuous=false;r.interimResults=false;r.onresult=e=>{setQuestion(e.results[0]?.[0]?.transcript||'');};r.onerror=e=>setError({message:e.error==='not-allowed'?'Microphone access was declined. Enable it in browser settings, or type your question.':'Voice input was interrupted. Try again or type your question.',code:'VOICE_INPUT_UNAVAILABLE'});r.onend=()=>setListening(false);setError(null);setListening(true);try{r.start();}catch{setListening(false);setError({message:'Microphone could not be started. Type your question.',code:'VOICE_INPUT_UNAVAILABLE'});}}
 async function send(){const text=question.trim();if(!text||busy)return;stopSpeech();recognition.current?.stop();setError(null);const conversation:Message[]=[...messages,{role:'user',content:text}];if(conversation.length>19){setError({message:'Start a new conversation before sending another question.',code:'CONVERSATION_LIMIT'});return;}setMessages(conversation);setQuestion('');setBusy(true);const controller=new AbortController();pending.current=controller;try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'chat',language:prefs.language,messages:conversation}),signal:controller.signal}),d=await r.json();if(!r.ok)throw Object.assign(Error(d.error),{code:d.code});if(typeof d.reply!=='string'||!d.reply.trim())throw Error('CitizenAI returned an empty reply.');setMessages([...conversation,{role:'assistant',content:d.reply}]);if(prefs.readAloud)void speak(d.reply);}catch(e){setMessages(conversation.slice(0,-1));setQuestion(text);setError({message:e instanceof Error&&e.name==='AbortError'?'The conversation request was cancelled.':e instanceof Error?e.message:'CitizenAI could not respond.',code:(e as {code?:string}).code||'AI_CONNECTION_INTERRUPTED'});}finally{setBusy(false);pending.current=null;}}
 return <section className="citizen-ai" data-ai-theme={prefs.theme}><header className="ai-header"><div><span className="chip purple"><Sparkles size={15}/> CitizenAI</span><h1>Your Citizen assistant</h1><p>Investments, careers and your connected workspaces.</p></div><button className="button" aria-expanded={settings} onClick={()=>setSettings(!settings)}><Settings2 size={18}/> Preferences</button></header>
 {settings&&<div className="ai-settings readiness-form"><label>Language<select value={prefs.language} onChange={e=>setPrefs({...prefs,language:e.target.value as AIPreferences['language']})}><option value="en">English</option><option value="st">Sesotho</option><option value="zu">isiZulu</option></select></label><label>Appearance<select value={prefs.theme} onChange={e=>setPrefs({...prefs,theme:e.target.value as 'dark'|'light'})}><option value="dark">Dark</option><option value="light">Light</option></select></label><label className="checkbox-label"><input type="checkbox" checked={prefs.readAloud} onChange={e=>setPrefs({...prefs,readAloud:e.target.checked})}/>Read replies aloud</label><p className="muted">Cloud speech uses the same Core voices as the app. Device voices provide a fallback where available. Sesotho voice input currently uses English recognition; check the transcript before sending. Microphone audio is processed by your browser’s speech service.</p><button className="button" onClick={()=>void savePreferences()}>Save preferences</button></div>}
 {saved&&<p role="status">{saved}</p>}{status&&!status.chat&&<p className="access-error">The shared Core AI provider is not configured yet. Other Hub services remain available.</p>}
 <div className="ai-conversation" role="log" aria-label="Conversation with CitizenAI" aria-live="polite">{!messages.length&&<div className="ai-welcome"><div className="brand-orb"/><h2>How can I help?</h2><div className="journey-options">{['How do I subscribe for shares?','Where can I apply for a position?','How do I track my investment?'].map(q=><button className="button" key={q} onClick={()=>setQuestion(q)}>{q}</button>)}</div></div>}{messages.map((m,i)=><article className={`ai-message ${m.role}`} key={i}><strong>{m.role==='user'?'You':'CitizenAI'}</strong><p>{m.content}</p>{m.role==='assistant'&&<button className="icon-button" aria-label="Read this reply aloud" onClick={()=>void speak(m.content)}><Volume2 size={18}/></button>}</article>)}{busy&&<p role="status">CitizenAI is considering your question…</p>}<div ref={end}/></div>
 {error&&<div className="inline-error" role="alert"><p>{error.message}</p><small>Issue: {error.code}</small><div className="actions">{error.code==='SIGN_IN_REQUIRED'?<a className="button" href="/login?next=/ai">Sign in again</a>:<button className="button" disabled={busy||!question.trim()} onClick={()=>void send()}>Retry question</button>}<a className="button" href="/">Return to workspace</a><button className="button" onClick={()=>setError(null)}>Dismiss</button></div></div>}
 <form className="ai-compose" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="ai-question">Your question</label><textarea id="ai-question" rows={2} maxLength={4000} placeholder="Ask CitizenAI…" value={question} disabled={busy} onChange={e=>setQuestion(e.target.value)}/><button type="button" className="icon-button" disabled={busy} aria-label={listening?'Stop voice input':'Start voice input'} aria-pressed={listening} onClick={dictate}><Mic/></button>{busy?<button type="button" className="button" onClick={()=>pending.current?.abort()}>Cancel</button>:<button type="submit" className="button primary" disabled={!question.trim()}><Send size={18}/> Send</button>}</form>
 <footer className="ai-footer">{speaking&&<button className="button" onClick={stopSpeech}><Square size={16}/>Stop speech</button>}<button className="button" disabled={busy} onClick={()=>{stopSpeech();setMessages([]);setError(null);setQuestion('');}}>New conversation</button><a href="/careers">Careers</a><a href="/opportunities">Investments</a><a href="/profile">My profile</a><p>Messages are sent to the configured AI providers when you press Send. Avoid passwords and confidential applicant documents. AI can make mistakes; review important details in the relevant workspace. Conversations are kept in this page’s memory.</p></footer></section>;
}
