
import { Panel,Hero,Metrics,Documents,Events,Empty } from "./BoardView";
import { Icon } from "./Icon";
import { money,type Overview } from "@/lib/data";
import type { Person } from "@/lib/contracts";
import {SubscriptionPortfolio} from './SubscriptionPortfolio';
export function InvestorView({person,data}:{person:Person;data:Overview}){
 const valid=data.investments.filter(item=>item.status!=='cancelled');
 const total=valid.reduce((sum,item)=>sum+Number(item.amount),0),shares=valid.reduce((sum,item)=>sum+Number(item.shares),0);
 const issued=valid.filter(item=>item.status==='issued').reduce((sum,item)=>sum+item.shares,0);
 return <><Hero title={`Welcome back, ${person.display_name.split(' ')[0]}`} subtitle="Thank you for being part of Citizen Bank’s journey." description="Here is an overview of your investment and key updates." kind="investor"/>
 <div className="dashboard-layout"><div className="primary-column"><Metrics items={[{icon:'finance',label:'Total commitment',value:money(total),detail:'Your recorded investment commitments'},{icon:'investors',label:'Shares subscribed',value:shares.toLocaleString(),detail:'Across your subscriptions'},{icon:'check',label:'Shares issued',value:issued.toLocaleString(),detail:'Recorded issued ownership'},{icon:'documents',label:'Investment documents',value:String(data.documents.length),detail:'Permissioned Google Drive links'}]}/>
 <div className="content-grid"><Panel title="Capital Raising Progress"><p className="panel-subtitle">Institutional commitments · Licensing & setup</p><div className="raising-progress"><div className="progress-track"><i style={{width:`${Math.min(100,Number(data.capital.committed)/25000000*100)}%`}}/></div><strong>{money(data.capital.committed)}</strong><small>Recorded against a {money(25000000)} planning target</small></div><div className="raising-stats"><div><strong>{money(data.capital.received)}</strong><small>Received & issued</small></div><div><strong>{money(Math.max(0,25000000-Number(data.capital.committed)))}</strong><small>Remaining to planning target</small></div></div></Panel>
 <Panel title="Your Share Allocation"><div className="capital-display"><div className="donut" style={{'--progress':`${shares?issued/shares*100:0}%`} as React.CSSProperties}><span><strong>{shares.toLocaleString()}</strong><small>Shares subscribed</small></span></div><div><p><i className="legend-dot"/>Issued<br/><strong>{issued.toLocaleString()}</strong></p><p>Awaiting issuance<br/><strong>{(shares-issued).toLocaleString()}</strong></p></div></div></Panel>
 <Panel title="Investment Timeline"><div className="milestone-track"><span className={valid.length?'complete':''}>Interest</span><span className={valid.some(i=>['committed','received','issued'].includes(i.status))?'complete':''}>Commitment</span><span className={valid.some(i=>['received','issued'].includes(i.status))?'complete':''}>Receipt</span><span className={issued?'complete':''}>Issuance</span></div><p className="muted">Your recorded investment milestones. Future regulatory approval is not assumed.</p></Panel><Panel title="Expected Returns"><div className="forecast-placeholder"><div className="forecast-grid"/><span className="chip purple">Coming soon</span><p>Approved investment projections will appear here when available.</p></div></Panel>
 <Panel title="Your Investment Portfolio" className="span-2"><p className="panel-subtitle">Your subscriptions and ownership records</p>{valid.length?<div className="table-scroll"><table><thead><tr><th>Instrument</th><th>Shares</th><th>Commitment</th><th>Status</th></tr></thead><tbody>{valid.map(item=><tr key={item.id}><td>{item.instrument}</td><td>{item.shares.toLocaleString()}</td><td>{money(item.amount,item.currency)}</td><td><span className={`chip ${item.status==='issued'?'success':''}`}>{item.status}</span></td></tr>)}</tbody></table></div>:<Empty>No confirmed investment records yet. Review opportunities and track subscriptions in your private portfolio.</Empty>}</Panel>
 <Panel title="My share subscriptions" className="span-2"><SubscriptionPortfolio person={person}/></Panel>
 <Panel title="Key Documents" link="/documents"><Documents data={data}/></Panel><Panel title="Institutional Updates" link="/communications">{data.notifications.slice(0,3).map(item=><a className="update-row" key={item.id} href={item.path}><span className="tone-icon tone-0"><Icon name="file"/></span><span><strong>{item.title}</strong><small>{item.body}</small></span></a>)}{!data.notifications.length&&<Empty>No updates yet.</Empty>}</Panel></div></div>
 <aside className="context-column"><Panel title="Investor Actions"><div className="investor-actions">{[{label:'Explore investment opportunities',icon:'investors',href:'/opportunities'},{label:'View investment documents',icon:'documents',href:'/documents'},{label:'Update investor information',icon:'profile',href:'/profile'},{label:'View institutional updates',icon:'communications',href:'/communications'},{label:'Security and preferences',icon:'settings',href:'/settings'}].map((action,index)=><a className={`investor-action tone-${index%4}`} href={action.href} key={action.label}><Icon name={action.icon}/><span>{action.label}</span><span>›</span></a>)}<div className="investor-action disabled"><Icon name="file"/><span>View share certificate<small>Coming soon</small></span></div><a className="investor-action" href="/opportunities"><Icon name="investors"/><span>Subscribe for Shares</span></a><a className="investor-action" href="/dataroom"><Icon name="documents"/><span>Investor data room</span></a><div className="investor-action disabled"><Icon name="communications"/><span>Send a message<small>Coming soon</small></span></div></div></Panel><Panel title="Investor Calendar"><Events data={data}/></Panel><Panel title="One Citizen Profile"><p className="muted">Your permitted roles share one identity. Update your common information once and manage each role’s responsibilities in its own workspace.</p><a className="button" href="/profile">Manage profile</a></Panel></aside></div></>;
}
