"use client";
import { useState } from "react";
import type { Person } from "@/lib/contracts";
export function ProfileForm({person}:{person:Person}){
 const fields=[{key:'full_name',label:'What name should we use for your profile?',hint:'Your shared name across Citizen services.'},{key:'phone',label:'What is your contact number?',hint:'Include the country code.'},{key:'country',label:'Where do you live?',hint:'Your country of residence.'},{key:'street_address',label:'What is your street address?',hint:'Shared contact information.'},{key:'city',label:'What city do you live in?',hint:'Your city of residence.'},{key:'employer',label:'Who is your employer?',hint:'Optional shared employment information.'},{key:'occupation',label:'What is your occupation?',hint:'Help us keep your profile current.'},{key:'bio',label:'What would you like to add about yourself?',hint:'Optional profile summary.'},...(person.roles.some(role=>['investor','shareholder'].includes(role))?[{key:'source_of_funds',label:'What is your source of investment funds?',hint:'Maintained in your investor profile.'},{key:'investor_type',label:'What type of investor are you?',hint:'For example, individual or organisation.'},{key:'investment_purpose',label:'What is your investment purpose?',hint:'Your goals for participating in Citizen.'}]:[])];
 const [step,setStep]=useState(0),[values,setValues]=useState<Record<string,string>>({full_name:person.display_name,phone:person.phone||'',country:person.country||'',occupation:person.occupation||'',bio:person.bio||'',street_address:person.street_address||'',city:person.city||'',employer:person.employer||'',...(person.roles.some(role=>['investor','shareholder'].includes(role))?{source_of_funds:person.role_profiles?.investor?.source_of_funds||'',investor_type:person.role_profiles?.investor?.investor_type||'',investment_purpose:person.role_profiles?.investor?.investment_purpose||''}:{})}),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState(false);
 async function save(){setBusy(true);setError(null);try{const response=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,version:person.version})});const data=await response.json();if(!response.ok)throw new Error(`${data.error} (${data.code})`);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Your profile could not be saved. Retry.');}finally{setBusy(false);}}
 if(saved)return <div className="guided-form" role="status"><h2>Your profile is updated</h2><p>Your common details belong to your Citizen identity. Role-specific information remains within its permitted workspace.</p><a className="button primary" href="/profile">View updated profile</a></div>;
 const field=fields[step];
 return <section className="guided-form"><div className="step-progress"><span>YOUR CITIZEN PROFILE</span><small>{step+1} of {fields.length}</small></div><div className="progress-track"><i style={{width:`${(step+1)/fields.length*100}%`}}/></div><h2>{field.label}</h2><p>{field.hint}</p><label className="sr-only" htmlFor="profile-answer">{field.label}</label>{field.key==='bio'?<textarea id="profile-answer" value={values[field.key]} onChange={e=>setValues({...values,[field.key]:e.target.value})} maxLength={2000}/>:<input id="profile-answer" value={values[field.key]} onChange={e=>setValues({...values,[field.key]:e.target.value})} maxLength={['source_of_funds','investment_purpose'].includes(field.key)?2000:field.key==='street_address'?300:field.key==='full_name'?150:field.key==='phone'?30:100} autoComplete={field.key==='full_name'?'name':field.key==='phone'?'tel':'off'}/>}{error&&<div className="form-error" role="alert">{error}{error.includes("PROFILE_CHANGED")&&<button className="button" onClick={()=>location.reload()}>Reload current profile</button>}</div>}<div className="button-row">{step>0&&<button className="button" onClick={()=>setStep(step-1)}>Back</button>}<button className="button primary" disabled={busy||!values.full_name.trim()} onClick={()=>step<fields.length-1?setStep(step+1):void save()}>{busy?'Saving…':step<fields.length-1?'Continue →':'Save profile'}</button><a className="button subtle" href="/profile">Cancel</a></div></section>;
}
