"use client";
import {useEffect,useState} from 'react';
export function RecoveryForm({code,requestId}:{code?:string;requestId?:string}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[warning,setWarning]=useState('');
 useEffect(()=>{if(code)history.replaceState(null,'','/reset-password');},[code]);
 const invalidLink=!!code&&(!/^[a-z0-9]{45}$/i.test(code)||!requestId);
 async function send(){setBusy(true);setError('');try{const r=await fetch('/api/auth/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(code?{action:'reset',code,request_id:requestId,password}:{action:'send',email}),signal:AbortSignal.timeout(45000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?`${d.error} (${d.code})`:'Recovery could not be completed. Retry or return to sign-in.');setMessage(d.message);setWarning(d.warning||'');if(code){setPassword('');setConfirm('');}}catch(e){setError(e instanceof Error&&e.name==='TimeoutError'?'The request timed out. If saving a password, try signing in first; otherwise retry or request a new email.':e instanceof Error?e.message:'The connection was interrupted. Retry or return to sign-in.');}finally{setBusy(false);}}
 return <div className="access-card"><img src="/brand/logo.webp" alt="Citizen Bank"/><h1>{code?'Set your Citizen password':'Activate or recover your account'}</h1><p>Use the email already recorded for your Citizen profile. Investors, shareholders and administrators use the same recovery process. WhatsApp and SMS recovery are coming soon.</p>
 {invalidLink?<section role="alert"><p>This recovery link is incomplete. Open the full link from your email or request a new one.</p><a className="button primary" href="/reset-password">Request a new link</a></section>:message?<section role="status"><p>{message}</p>{warning&&<p role="alert">{warning}</p>}<div className="button-row"><a className="button primary" href="/login">Return to sign-in</a>{!code&&<button className="button" type="button" onClick={()=>setMessage('')}>Use another email / resend</button>}</div></section>:<form onSubmit={e=>{e.preventDefault();void send();}}>
 {code?<><label>New password<input required type="password" autoComplete="new-password" minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm password<input required type="password" autoComplete="new-password" maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="muted">Use at least 12 characters. The identity provider also applies its password requirements.</p>{confirm&&password!==confirm&&<p role="status">The passwords must match.</p>}</>:<label>Your email<input required type="email" maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}
 {error&&<div role="alert" className="form-error"><p>{error}</p><button className="button" type="button" onClick={()=>setError('')}>Edit and retry</button>{code&&<a className="button" href="/reset-password">Request a new recovery link</a>}<a className="button" href="/login">Cancel</a></div>}<button className="button primary full" disabled={busy||!!code&&(password!==confirm||password.length<12)}>{busy?'Please wait…':code?'Save new password':'Send recovery email'}</button></form>}
 <a className="access-return" href="/login">← Back to sign-in</a><a className="access-return" href={process.env.NEXT_PUBLIC_WEBSITE_URL}>Back to Citizen Bank website</a></div>;
}
