"use client";
import {useState} from 'react';
import {transitions,validTransition} from '@/lib/recruitment-policy';
import type {Vacancy,Application} from '@/lib/recruitment';
async function post(data:unknown){const r=await fetch('/api/recruitment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(15000)}),d=await r.json();if(!r.ok)throw Object.assign(Error(d.error||'The request could not be completed.'),{code:d.code});return d;}
function Issue({message,retry}:{message:string;retry:()=>void}){return <div className="inline-error" role="alert"><p>{message}</p><div className="actions"><button className="button" type="button" onClick={retry}>Retry</button><button className="button" type="button" onClick={()=>window.location.reload()}>Reload latest information</button><a className="button" href="/careers">Cancel</a></div></div>;}
export function ShareVacancy({id}:{id:string}){const [message,setMessage]=useState('');return <><button className="button" onClick={async()=>{try{const url=new URL('/careers?position='+id,window.location.origin).href;if(typeof navigator.share==='function'){await navigator.share({title:'Citizen career opportunity',url});setMessage('Shared.');}else{await navigator.clipboard.writeText(url);setMessage('Link copied.');}}catch(e){setMessage(e instanceof Error&&e.name==='AbortError'?'Sharing cancelled.':'Copy the page address to share this position.');}}}>Share opening</button>{message&&<small role="status">{message}</small>}</>;}
export function ApplicationForm({vacancy,name}:{vacancy:Vacancy;name:string}){
 const [step,setStep]=useState(0),[statement,setStatement]=useState(''),[cv,setCV]=useState(''),[references,setReferences]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[key]=useState(()=>crypto.randomUUID());
 async function submit(){if(busy)return;setBusy(true);setError('');try{await post({action:'apply',vacancy_id:vacancy.id,vacancy_version:vacancy.version,request_key:key,cover_statement:statement,cv_link:cv,references_link:references,consent});window.location.assign('/careers#applications');}catch(e){setError(e instanceof Error?e.message:'Your application could not be saved.');setBusy(false);}}
 return <form className="subscription-journey readiness-form" onSubmit={e=>{e.preventDefault();if(step<4)setStep(step+1);else void submit();}}><div className="journey-progress"><span>Application for {vacancy.title}</span><span>{step+1} of 5</span></div><progress value={step+1} max={5}/>
 {step===0&&<><h2>Let’s start with your Citizen profile</h2><p>Applying as <strong>{name}</strong>. We use the contact details already in your profile.</p><a href="/profile?edit=1">Check or update my profile ↗</a><p className="muted">Shareholder or investor status does not affect recruitment decisions. Appointments are subject to assessment and approval.</p></>}
 {step===1&&<label htmlFor="career-statement">What makes you suited to this position?<textarea id="career-statement" required minLength={30} maxLength={5000} value={statement} onChange={e=>setStatement(e.target.value)} autoFocus/><small>Your cover statement: experience, motivation and relevant strengths.</small></label>}
 {step===2&&<label htmlFor="career-cv">Where can we find your CV?<input id="career-cv" type="url" required value={cv} onChange={e=>setCV(e.target.value)} placeholder="Google Drive document shared link" autoFocus/><small>Upload your CV to Google Drive, then paste its file link here. Grant access to your intended recruitment reviewers; avoid making personal documents public. Citizen stores the link only.</small></label>}
 {step===3&&<label htmlFor="career-references">Do you have professional reference information?<input id="career-references" type="url" value={references} onChange={e=>setReferences(e.target.value)} placeholder="Optional Google Drive shared link" autoFocus/><small>The source adverts request three references. If they are not ready, you can provide them during the checks stage. Obtain consent before sharing another person’s details.</small></label>}
 {step===4&&<><h2>Review and submit</h2><p><strong>{vacancy.title}</strong> · {name}</p><p className="application-statement">{statement}</p><a href={cv} target="_blank" rel="noopener noreferrer">Review your CV ↗</a><label className="checkbox-label"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I confirm this application is accurate and authorise the recruitment team to review my profile and the linked documents for this application.</label><p className="muted">Submission is not an appointment. You can follow progress and withdraw privately in My applications.</p></>}
 {error&&<Issue message={error} retry={()=>void submit()}/>}<div className="actions">{step>0&&<button className="button" type="button" disabled={busy} onClick={()=>setStep(step-1)}>Back</button>}<button className="button primary" disabled={busy}>{busy?'Submitting…':step===4?'Submit application':'Continue'}</button><a className="button" href="/careers">Cancel</a></div></form>;
}
export function CandidateResponse({application,status,label}:{application:Application;status:'accepted'|'declined'|'withdrawn';label:string}){const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');async function act(){setBusy(true);setError('');try{await post({action:'candidate',id:application.id,version:application.version,status,confirmed:true});window.location.reload();}catch(e){setError(e instanceof Error?e.message:'Response could not be saved.');setBusy(false);}}return <div>{!confirm?<button className="button" onClick={()=>setConfirm(true)}>{label}</button>:<><p>{status==='accepted'?'I have reviewed the linked offer and want to accept its terms. Final appointment remains subject to approvals.':status==='declined'?'Decline this offer? This closes this application.':'Withdraw this application? This action closes it.'}</p><button className="button primary" disabled={busy} onClick={()=>void act()}>Confirm {label.toLowerCase()}</button><button className="button" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></>}{error&&<Issue message={error} retry={()=>void act()}/>}</div>;}
export function ApplicationDocuments({application:a}:{application:Application}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <details><summary>Update CV or references</summary><form className="readiness-form" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await post({action:'documents',id:a.id,version:a.version,cv_link:d.get('cv_link'),references_link:d.get('references_link')});window.location.reload();}catch(e){setError(e instanceof Error?e.message:'Documents could not be saved.');setBusy(false);}}}><label>CV shared link<input name="cv_link" type="url" required defaultValue={a.cv_link}/></label><label>References shared link<input name="references_link" type="url" defaultValue={a.references_link??''}/></label>{error&&<p role="alert">{error}</p>}<button className="button" disabled={busy}>Save document links</button></form></details>;}
export function CareerNotifications({initial}:{initial:boolean}){const [enabled,setEnabled]=useState(initial),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <div><label className="checkbox-label"><input type="checkbox" checked={enabled} disabled={busy} onChange={async e=>{const value=e.target.checked;setBusy(true);try{await post({action:'notifications',enabled:value});setEnabled(value);setMessage('Career notification preference saved.');}catch(e){setMessage(e instanceof Error?e.message:'Preference could not be saved. Retry.');}finally{setBusy(false);}}}/>Notify me about new career openings in Citizen Hub</label><p className="muted">Available to investors and shareholders. Application updates are always shown privately in My applications and Communications. Email delivery is being connected.</p>{message&&<p role="status">{message}</p>}</div>;}
export function VacancyForm({vacancy}:{vacancy?:Vacancy}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(form:HTMLFormElement){const d=new FormData(form);setBusy(true);setError('');try{await post({action:'vacancy',...(vacancy?{id:vacancy.id,version:vacancy.version}:{}),vacancy:{title:d.get('title'),summary:d.get('summary'),requirements:d.get('requirements'),location:d.get('location'),kind:d.get('kind'),phase:d.get('phase'),closes_at:new Date(String(d.get('closes_at'))).toISOString(),source_link:d.get('source_link'),status:d.get('status')}});window.location.assign('/recruitment');}catch(e){setError(e instanceof Error?e.message:'Vacancy could not be saved.');setBusy(false);}}
 return <form className="readiness-form" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><label>Position title<input name="title" defaultValue={vacancy?.title} required minLength={3} maxLength={150}/></label><label>Role summary<textarea name="summary" defaultValue={vacancy?.summary} required minLength={20} maxLength={5000}/></label><label>Responsibilities and qualifications<textarea name="requirements" defaultValue={vacancy?.requirements} required minLength={20} maxLength={5000}/></label><label>Location<input name="location" defaultValue={vacancy?.location??'Lesotho / Southern Africa'} required/></label><label>Appointment type<select name="kind" defaultValue={vacancy?.kind??'employment'}><option value="employment">Employment</option><option value="board">Board appointment</option></select></label><label>Business phase<select name="phase" defaultValue={vacancy?.phase??'pre_licensing'}><option value="pre_licensing">Pre-licensing</option><option value="post_licensing">Post-licensing</option><option value="both">Succession across both phases</option></select></label><label>Closing date and time (your device’s local time)<input type="datetime-local" name="closes_at" required defaultValue={vacancy?localDate(vacancy.closes_at):''}/></label><label>Google Drive source advertisement<input type="url" name="source_link" defaultValue={vacancy?.source_link} required/></label><label>Publication status<select name="status" defaultValue={vacancy?.status??'draft'}>{['draft','open','paused','closed','filled'].map(s=><option key={s} value={s}>{s}</option>)}</select></label><p className="muted">Publishing makes this vacancy visible and sends one in-app notice to subscribed investors/shareholders. Reopening does not duplicate the notice. Current appointments are not changed.</p>{error&&<p className="inline-error" role="alert">{error} Edit and retry, or reload if the record changed.</p>}<div className="actions"><button className="button primary" disabled={busy}>{busy?'Saving…':'Save position'}</button><a href="/recruitment" className="button">Cancel</a></div></form>;
}
function localDate(value:string){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function ApplicationReview({application:a}:{application:Application}){
 const next=(transitions[a.status]??[]).filter(s=>validTransition(a.status,s,a.kind)&&!['withdrawn','accepted','declined'].includes(s)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!next.length)return <p className="muted">{a.status==='offered'?'Waiting for the candidate to accept or decline the offer.':'No further admin steps are available.'}</p>;
 async function submit(form:HTMLFormElement){const d=new FormData(form);setBusy(true);setError('');try{await post({action:'review',id:a.id,version:a.version,status:d.get('status'),candidate_note:d.get('candidate_note'),offer_link:d.get('offer_link'),contract_link:d.get('contract_link'),approval_link:d.get('approval_link'),regulatory_link:d.get('regulatory_link'),start_date:d.get('start_date'),conditions_confirmed:d.get('conditions_confirmed')==='on'});window.location.reload();}catch(e){setError(e instanceof Error?e.message:'Review could not be saved.');setBusy(false);}}
 return <form className="readiness-form" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><label>Next step<select name="status">{next.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Update visible to the candidate<textarea name="candidate_note" required minLength={5} maxLength={3000} placeholder="Explain the next step, interview arrangements or requested documents."/></label>{[['offer_link','Approved offer',a.offer_link],['contract_link','Signed agreement / acceptance',a.contract_link],['approval_link','Company appointment approval',a.approval_link],['regulatory_link','Regulatory approval evidence (board)',a.regulatory_link]].map(([name,label,value])=><label key={name}>{label}<input name={name!} type="url" placeholder="Google Drive shared link" defaultValue={value??''}/></label>)}<label>Start date<input name="start_date" type="date" defaultValue={a.start_date?.slice(0,10)??''}/></label><label className="checkbox-label"><input name="conditions_confirmed" type="checkbox" defaultChecked={a.conditions_confirmed}/>I have reviewed the linked evidence and confirm all appointment and onboarding conditions are met.</label><p className="muted">These documents stay in Drive. Share only with the relevant candidate and authorised reviewers. Employment decisions remain human decisions. This workflow does not grant system roles or replace corporate-register reconciliation.</p>{error&&<p className="inline-error" role="alert">{error} Correct the information and retry, or reload the latest record.</p>}<button className="button primary" disabled={busy}>{busy?'Saving…':'Save next step'}</button></form>;
}

