"use client";
import {useState} from 'react';
import type {Opportunity} from '@/lib/investments';
import type {Person} from '@/lib/contracts';
const money=(amount:number|string,currency='LSL')=>new Intl.NumberFormat('en-ZA',{style:'currency',currency,maximumFractionDigits:2}).format(Number(amount));
export function SubscriptionForm({offer,person}:{offer:Opportunity;person:Person}){
 const [step,setStep]=useState(0),[units,setUnits]=useState(offer.min_units),[source,setSource]=useState(person.role_profiles?.investor?.source_of_funds||''),[purpose,setPurpose]=useState(person.role_profiles?.investor?.investment_purpose||''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[changed,setChanged]=useState(false),[saved,setSaved]=useState(false),[requestKey]=useState(()=>crypto.randomUUID());
 async function submit(){setBusy(true);setError('');try{const r=await fetch('/api/investments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_key:requestKey,opportunity_id:offer.id,version:offer.version,units,source_of_funds:source,purpose,consent}),signal:AbortSignal.timeout(15000)});const d=await r.json().catch(()=>({}));if(!r.ok){setChanged(r.status===409);throw new Error(d.error||'Your request could not be submitted.');}setSaved(true);}catch(e){setError(e instanceof Error?e.message:'The connection was interrupted. Retry uses the same request reference.');}finally{setBusy(false);}}
 if(saved)return <section role="status"><h2>Subscription request received</h2><p>Your request is awaiting review. Track it below for your unsigned certificate preview, agreement, invoice and payment status. No payment was taken and no shares were issued.</p><a className="button primary" href="/opportunities">View my requests</a></section>;
 const ready=step===0?Number.isInteger(units)&&units>=offer.min_units&&units<=offer.max_units:step===1?source.trim().length>=3:step===2?purpose.trim().length>=3:consent;
 return <form className="readiness-form" onSubmit={e=>{e.preventDefault();if(!ready)return;if(step<3)setStep(s=>s+1);else void submit();}}><p className="muted">{person.display_name} · {person.email} · Question {step+1} of 4</p>
 {step===0&&<label>How many reference shares would you like to subscribe for?<input autoFocus required type="number" min={offer.min_units} max={offer.max_units} step="1" value={units} onChange={e=>setUnits(Number(e.target.value))}/><small>{money(offer.unit_price,offer.currency)} per reference share · {offer.min_units}–{offer.max_units} shares</small></label>}
 {step===1&&<label>What is the source of your investment funds?<textarea autoFocus required minLength={3} maxLength={2000} value={source} onChange={e=>setSource(e.target.value)}/></label>}
 {step===2&&<label>What is your investment objective?<textarea autoFocus required minLength={3} maxLength={2000} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label>}
 {step===3&&<><h2>Review your request</h2><p>{offer.title} · {units} shares · {money(units*Number(offer.unit_price),offer.currency)}</p><p>{source}</p><p>{purpose}</p>{offer.terms_link&&<a href={offer.terms_link} target="_blank" rel="noopener noreferrer">Read the opportunity terms in Google Drive ↗</a>}<label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I request a subscription review. I understand this does not transfer money, issue shares, or establish a confirmed holding.</label></>}
 {error&&<div className="access-error" role="alert"><p>{error}</p>{changed?<a className="button" href="/opportunities">Reload opportunities</a>:<button className="button" type="button" disabled={busy} onClick={()=>void submit()}>Retry submission</button>}<button className="button" type="button" onClick={()=>setError('')}>Dismiss</button></div>}
 <div className="actions">{step>0&&<button className="button" type="button" disabled={busy} onClick={()=>setStep(s=>s-1)}>Back</button>}<button className="button primary" disabled={busy||!ready||changed}>{busy?'Submitting…':step===3?'Submit subscription request':'Continue'}</button><a className="button" href="/opportunities">Cancel</a></div></form>;
}
