"use client";
import {useState} from 'react';
import type {Opportunity} from '@/lib/investments';
import type {Person} from '@/lib/contracts';
import {SubscriptionPayment} from './SubscriptionPayment';
import {subscriptionAmount} from '@/lib/subscription-money';
const money=(amount:number|string,currency='LSL')=>new Intl.NumberFormat('en-ZA',{style:'currency',currency,maximumFractionDigits:2}).format(Number(amount));
export function SubscriptionForm({offer,person}:{offer:Opportunity;person:Person}){
 const [step,setStep]=useState(0),[units,setUnits]=useState(offer.min_units),[source,setSource]=useState(person.role_profiles?.investor?.source_of_funds||''),[purpose,setPurpose]=useState(person.role_profiles?.investor?.investment_purpose||''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[changed,setChanged]=useState(false),[saved,setSaved]=useState(''),[requestKey]=useState(()=>crypto.randomUUID());
 async function submit(){setBusy(true);setError('');try{const r=await fetch('/api/investments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_key:requestKey,opportunity_id:offer.id,version:offer.version,units,source_of_funds:source,purpose,consent}),signal:AbortSignal.timeout(30000)});const d=await r.json().catch(()=>({}));if(!r.ok){setChanged(r.status===409);throw new Error(d.error||'Your subscription could not be saved.');}if(typeof d.id!=='string')throw new Error('The saved subscription reference was missing. Retry uses the same reference.');setSaved(d.id);}catch(e){setError(e instanceof Error?e.message:'The connection was interrupted. Retry uses the same request reference.');}finally{setBusy(false);}}
 if(saved)return <SubscriptionPayment id={saved} amount={money(units*Number(offer.unit_price),offer.currency)}/>;
 const ready=step===0?Number.isInteger(units)&&units>=offer.min_units&&units<=offer.max_units:step===1?source.trim().length>=3:step===2?purpose.trim().length>=3:consent;
 return <form className="readiness-form subscription-journey" onSubmit={e=>{e.preventDefault();if(!ready||busy)return;if(step<3)setStep(s=>s+1);else void submit();}}><div className="journey-progress"><span>Subscribe for Shares</span><span>Step {step+1} of 4</span></div><progress aria-label="Subscription progress" max={4} value={step+1}/><p className="muted">{person.display_name} · {person.email}</p>
 {step===0&&<><label>How many shares would you like to subscribe for?<input autoFocus required type="number" min={offer.min_units} max={offer.max_units} step="1" value={units} onChange={e=>setUnits(Number(e.target.value))}/><small>{money(offer.unit_price,offer.currency)} per reference share · {offer.min_units.toLocaleString()}–{offer.max_units.toLocaleString()} shares</small></label><div className="journey-options" aria-label="Suggested quantities">{[offer.min_units,offer.min_units*2,offer.min_units*5].filter(value=>value<=offer.max_units).map(value=><button type="button" className="button" key={value} onClick={()=>setUnits(value)}>{value.toLocaleString()} shares</button>)}</div><div className="investment-calculator" role="status"><span>Your subscription amount</span><strong>{Number.isSafeInteger(units)&&units>0?money(subscriptionAmount(units,offer.unit_price),offer.currency):'Enter a whole share quantity'}</strong><small>{units<offer.min_units?'Increase your quantity to meet the minimum.':units>offer.max_units?'Reduce your quantity to the published limit.':'Payment can be skipped and completed later.'}</small></div><p className="muted">SAFE reference shares describe a future conversion. Ownership percentages and returns are not confirmed by this calculator.</p></>}
 {step===1&&<label>What is the source of your investment funds?<textarea autoFocus required minLength={3} maxLength={2000} value={source} onChange={e=>setSource(e.target.value)}/></label>}
 {step===2&&<label>What is your investment objective?<textarea autoFocus required minLength={3} maxLength={2000} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label>}
 {step===3&&<><h2>Ready to complete your subscription?</h2><p>{offer.title} · {units} shares · {money(units*Number(offer.unit_price),offer.currency)}</p><p>{source}</p><p>{purpose}</p><p>You can skip payment and return to your private portfolio later. This offer is a SAFE for future ordinary shares, subject to authorised conversion.</p>{offer.terms_link&&<a href={offer.terms_link} target="_blank" rel="noopener noreferrer">Read the opportunity terms in Google Drive ↗</a>}<label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I have reviewed the SAFE terms. I understand my investment remains unconfirmed until payment evidence and settlement are verified and the signed agreement is accepted. Submitting alone does not issue shares or execute the contract.</label></>}
 {error&&<div className="access-error" role="alert"><p>{error}</p>{changed?<a className="button" href="/opportunities">Reload opportunities</a>:<button className="button" type="button" disabled={busy} onClick={()=>void submit()}>Retry submission</button>}<button className="button" type="button" onClick={()=>setError('')}>Dismiss</button></div>}
 <div className="actions">{step>0&&<button className="button" type="button" disabled={busy} onClick={()=>setStep(s=>s-1)}>Back</button>}<button className="button primary" disabled={busy||!ready||changed}>{busy?'Submitting…':step===3?'Subscribe for Shares':'Continue'}</button><a className="button" href="/opportunities">Cancel</a></div></form>;
}
