"use client";
import {useState} from 'react';
export function SubscriptionPayment({id,amount}:{id:string;amount:string}){
 const [step,setStep]=useState<'choice'|'proof'|'done'>('choice'),[link,setLink]=useState(''),[submitted,setSubmitted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/investments/'+id+'/payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment_link:link}),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Payment evidence could not be saved.');setSubmitted(true);setStep('done');}catch(e){setError(e instanceof Error?e.message:'Your connection was interrupted. Retry or skip for now.');}finally{setBusy(false);}}
 return <section className="subscription-journey" aria-label="Optional payment"><span className="chip">Subscription saved · payment optional</span>
 {step==='choice'&&<><h2>Have you paid for this subscription?</h2><p>Your subscription for {amount} is saved. Payment can happen outside the Hub. Use the approved payment instructions supplied with your agreement, or <a href="mailto:investors@citizenbank.co.ls">ask investor support for the payment instructions</a>.</p><div className="journey-options"><button className="button primary" onClick={()=>setStep('proof')}>I have paid — add proof</button><button className="button" onClick={()=>setStep('done')}>Skip payment for now</button></div></>}
 {step==='proof'&&<form onSubmit={e=>{e.preventDefault();void save();}}><h2><label htmlFor={'payment-link-'+id}>Where is your proof of payment in Google Drive?</label></h2><p>Upload your file to Google Drive, grant the Citizen administrator Viewer access and paste the shared file link below.</p><input id={'payment-link-'+id} autoFocus type="url" required value={link} onChange={e=>setLink(e.target.value)} placeholder="https://drive.google.com/file/d/…/view"/>{error&&<p className="access-error" role="alert">{error}</p>}<div className="actions"><button className="button" type="button" disabled={busy} onClick={()=>setStep('choice')}>Back</button><button className="button primary" disabled={busy||!link}>{busy?'Saving…':'Submit proof for review'}</button><button className="button" type="button" disabled={busy} onClick={()=>setStep('done')}>Skip for now</button></div></form>}
 {step==='done'&&<div role="status"><h2>{submitted?'Proof submitted for review':'Subscription saved — payment pending'}</h2><p>{submitted?'An administrator will review the evidence and reconcile settlement. Proof alone does not confirm receipt.':'Return to your private investment portfolio whenever you are ready to add proof of payment.'}</p><a className="button primary" href="/investors#subscriptions">View my investment portfolio</a><a className="button" href={'/subscriptions/'+id}>View subscription details</a></div>}
 <p className="journey-notice">Your investment remains unconfirmed until proof of payment is received, settlement verified and the signed SAFE agreement accepted. This subscription is not an executed contract or an issued share certificate.</p></section>;
}
