import 'server-only';
import {z} from 'zod';
import type {Person} from './contracts';
import {audited} from './audit';
import {ServiceIssue} from './db';
export const profileInput=z.object({full_name:z.string().trim().min(1).max(150).optional(),phone:z.string().max(30).optional(),country:z.string().max(100).optional(),street_address:z.string().max(300).optional(),city:z.string().max(100).optional(),bio:z.string().max(2000).optional(),occupation:z.string().max(100).optional(),employer:z.string().max(100).optional(),source_of_funds:z.string().max(2000).optional(),investor_type:z.string().max(100).optional(),investment_purpose:z.string().max(2000).optional(),version:z.number().int().positive()}).strict();
export async function updateProfile(person:Person,input:unknown){const update=profileInput.parse(input);const investorKeys=['source_of_funds','investor_type','investment_purpose'] as const;if(investorKeys.some(key=>update[key]!==undefined)&&!person.roles.some(role=>['investor','shareholder'].includes(role)))throw new ServiceIssue('INVESTOR_ROLE_REQUIRED','Investor information can only be maintained by an investor or shareholder.',403);
 const investor={...person.role_profiles?.investor};for(const key of investorKeys)if(update[key]!==undefined)investor[key]=update[key]!;
 const rows=await audited<Person>(`UPDATE hub_people SET display_name=$2,phone=$3,country=$4,street_address=$5,city=$6,bio=$7,occupation=$8,employer=$9,role_profiles=$10::jsonb,version=version+1,updated_at=now() WHERE id=$1 AND version=$11 RETURNING *`,[person.id,update.full_name??person.display_name,update.phone??person.phone,update.country??person.country,update.street_address??person.street_address??'',update.city??person.city??'',update.bio??person.bio,update.occupation??person.occupation,update.employer??person.employer??'',JSON.stringify({...person.role_profiles,investor}),update.version],person,'profile.updated','person');if(!rows[0])throw new ServiceIssue('PROFILE_CHANGED','Your profile changed elsewhere. Reload before saving.',409);return {...rows[0],roles:person.roles};}
export function sharedProfile(person:Person){return {full_name:person.display_name,phone:person.phone||'',country:person.country||'',street_address:person.street_address||'',city:person.city||'',bio:person.bio||'',occupation:person.occupation||'',employer:person.employer||'',...(person.roles.some(role=>['investor','shareholder'].includes(role))?person.role_profiles?.investor:{}),version:person.version};}
