import {z} from 'zod';
import {driveReference} from './contracts';
const drive=z.string().trim().max(2000).transform((v,ctx)=>{try{return driveReference(v).url;}catch{ctx.addIssue({code:'custom',message:'Use a Google Drive document shared link.'});return z.NEVER;}});
export const documentUpdate=z.object({action:z.literal('documents'),id:z.string().uuid(),version:z.number().int().positive(),cv_link:drive,references_link:z.union([drive,z.literal('')])}).strict();
export const vacancyInput=z.object({title:z.string().trim().min(3).max(150),summary:z.string().trim().min(20).max(5000),requirements:z.string().trim().min(20).max(5000),location:z.string().trim().min(2).max(150),kind:z.enum(['employment','board']),phase:z.enum(['pre_licensing','post_licensing','both']),closes_at:z.string().datetime({offset:true}),source_link:drive,status:z.enum(['draft','open','paused','closed','filled'])}).strict();
export const applicationInput=z.object({action:z.literal('apply'),vacancy_id:z.string().uuid(),vacancy_version:z.number().int().positive(),request_key:z.string().uuid(),cover_statement:z.string().trim().min(30).max(5000),cv_link:drive,references_link:z.union([drive,z.literal('')]).optional(),consent:z.literal(true)}).strict();
export const reviewInput=z.object({action:z.literal('review'),id:z.string().uuid(),version:z.number().int().positive(),status:z.enum(['under_review','shortlisted','interview','checks','offered','onboarding','employed','appointed','rejected']),candidate_note:z.string().trim().min(5).max(3000),offer_link:z.union([drive,z.literal('')]),contract_link:z.union([drive,z.literal('')]),approval_link:z.union([drive,z.literal('')]),regulatory_link:z.union([drive,z.literal('')]),start_date:z.union([z.string().date(),z.literal('')]),conditions_confirmed:z.boolean()}).strict();
export const transitions:Record<string,readonly string[]>={submitted:['under_review','rejected','withdrawn'],under_review:['shortlisted','rejected','withdrawn'],shortlisted:['interview','rejected','withdrawn'],interview:['checks','rejected','withdrawn'],checks:['offered','rejected','withdrawn'],offered:['accepted','declined','withdrawn'],accepted:['onboarding','withdrawn'],onboarding:['employed','appointed','withdrawn'],employed:[],appointed:[],rejected:[],withdrawn:[],declined:[]};
export function validTransition(from:string,to:string,kind:string){return !!transitions[from]?.includes(to)&&!(to==='appointed'&&kind!=='board')&&!(to==='employed'&&kind!=='employment');}
