import 'server-only';
import {query,ServiceIssue} from './db';
import {can,type Person} from './contracts';
import {applicationInput,reviewInput,validTransition} from './recruitment-policy';
export type Vacancy={id:string;title:string;summary:string;requirements:string;location:string;kind:'employment'|'board';phase:string;closes_at:string;status:string;source_link:string;version:number;published_at:string|null};
export type Application={id:string;vacancy_id:string;person_id:string;display_name:string;email:string;phone:string|null;title:string;kind:string;status:string;candidate_note:string;version:number;created_at:string;cv_link:string;cover_statement:string;references_link:string|null;offer_link:string|null;contract_link:string|null;approval_link:string|null;regulatory_link:string|null;start_date:string|null;conditions_confirmed:boolean};
export const recruiter=(person:Person)=>can(person.roles,['admin']);
export async function vacancies(person:Person|null){return query<Vacancy>(`SELECT * FROM hub_vacancies WHERE scope=$1 ${person&&recruiter(person)?'':"AND status='open' AND closes_at>now()"} ORDER BY closes_at,title`,[person?.scope??'live']);}
export async function applications(person:Person){return query<Application>(`SELECT a.*,p.display_name,p.email,p.phone,v.title,v.kind FROM hub_job_applications a JOIN hub_people p ON p.id=a.person_id AND p.scope=a.scope JOIN hub_vacancies v ON v.id=a.vacancy_id AND v.scope=a.scope WHERE a.scope=$1 ${recruiter(person)?'':'AND a.person_id=$2'} ORDER BY a.created_at DESC LIMIT 200`,recruiter(person)?[person.scope]:[person.scope,person.id]);}
export async function applicationEvents(person:Person){return query<{application_id:string;status:string;note:string;created_at:string}>(`SELECT e.application_id,e.status,e.note,e.created_at FROM hub_recruitment_events e JOIN hub_job_applications a ON a.id=e.application_id AND a.scope=e.scope WHERE a.scope=$1 ${recruiter(person)?'':'AND a.person_id=$2'} ORDER BY e.created_at DESC LIMIT 1000`,recruiter(person)?[person.scope]:[person.scope,person.id]);}
export async function apply(person:Person,input:unknown){const data=applicationInput.parse(input);
 const previous=await query<{id:string}>('SELECT id FROM hub_job_applications WHERE person_id=$1 AND scope=$2 AND request_key=$3',[person.id,person.scope,data.request_key]);if(previous[0])return previous[0];
 const rows=await query<{id:string}>(`WITH changed AS (INSERT INTO hub_job_applications(scope,vacancy_id,person_id,request_key,cover_statement,cv_link,references_link) SELECT $1,v.id,$2,$3,$4,$5,$6 FROM hub_vacancies v WHERE v.id=$7 AND v.scope=$1 AND v.version=$8 AND v.status='open' AND v.closes_at>now() RETURNING *),event AS (INSERT INTO hub_recruitment_events(application_id,scope,actor_id,status,note) SELECT id,scope,person_id,status,'Application submitted. Your profile and documents will be reviewed by authorised administrators.' FROM changed),logged AS (INSERT INTO hub_audit(actor_id,action,resource_type,resource_id,scope) SELECT $2,'recruitment.applied','application',id,scope FROM changed),notice AS (INSERT INTO hub_notifications(person_id,scope,title,body,path,source_key) SELECT person_id,scope,'Application received','Your application is saved. Follow its progress in My applications.','/careers#applications','application:'||id||':'||version FROM changed) SELECT id FROM changed`,[person.scope,person.id,data.request_key,data.cover_statement,data.cv_link,data.references_link||null,data.vacancy_id,data.vacancy_version]);
 if(!rows[0])throw new ServiceIssue('VACANCY_CHANGED','This vacancy changed or closed. Reload the careers page before applying.',409);return rows[0];}
export async function progress(person:Person,input:unknown){const data=reviewInput.parse(input);if(!recruiter(person))throw new ServiceIssue('RECRUITMENT_ACCESS_DENIED','Only administrators can manage recruitment.',403);
 const [current]=await query<Application>('SELECT a.*,v.kind FROM hub_job_applications a JOIN hub_vacancies v ON v.id=a.vacancy_id AND v.scope=a.scope WHERE a.id=$1 AND a.scope=$2',[data.id,person.scope]);
 if(!current)throw new ServiceIssue('APPLICATION_NOT_FOUND','This application is not available.',404);
 if(!validTransition(current.status,data.status,current.kind))throw new ServiceIssue('APPLICATION_TRANSITION_INVALID','That step is not available from the current application status. Reload and choose the next step.',409);
 if(['accepted','onboarding'].includes(current.status)&&data.offer_link!==current.offer_link)throw new ServiceIssue('ACCEPTED_OFFER_CHANGED','The accepted offer cannot be replaced during onboarding. Retain its existing link.',409);
 if(['offered','onboarding','employed','appointed'].includes(data.status)&&!data.offer_link)throw new ServiceIssue('OFFER_REQUIRED','Link the approved offer document in Google Drive.',422);
 if(['employed','appointed'].includes(data.status)&&(!data.conditions_confirmed||!data.contract_link||!data.approval_link||!data.start_date||data.status==='appointed'&&!data.regulatory_link))throw new ServiceIssue('APPOINTMENT_EVIDENCE_REQUIRED','Provide the signed agreement, company approval, start date and confirmed conditions. Board appointments also require regulatory approval evidence.',422);
 return change(person,current,data.status,data.candidate_note,data.version,data);}
async function change(person:Person,current:Application,status:string,note:string,version:number,data?:ReturnType<typeof reviewInput.parse>){
 const rows=await query<{id:string}>(`WITH changed AS (UPDATE hub_job_applications SET status=$4,candidate_note=$5,offer_link=$6,contract_link=$7,approval_link=$8,regulatory_link=$9,start_date=$10,conditions_confirmed=$11,version=version+1,updated_at=now() WHERE id=$1 AND scope=$2 AND version=$3 AND status=$12 RETURNING *),event AS (INSERT INTO hub_recruitment_events(application_id,scope,actor_id,status,note) SELECT id,scope,$13,status,candidate_note FROM changed),logged AS (INSERT INTO hub_audit(actor_id,action,resource_type,resource_id,scope) SELECT $13,'recruitment.progressed','application',id,scope FROM changed),notice AS (INSERT INTO hub_notifications(person_id,scope,title,body,path,source_key) SELECT person_id,scope,'Application update',candidate_note,'/careers#applications','application:'||id||':'||version FROM changed) SELECT id FROM changed`,[current.id,person.scope,version,status,note,data?data.offer_link||null:current.offer_link,data?data.contract_link||null:current.contract_link,data?data.approval_link||null:current.approval_link,data?data.regulatory_link||null:current.regulatory_link,data?data.start_date||null:current.start_date,data?data.conditions_confirmed:current.conditions_confirmed,current.status,person.id]);
 if(!rows[0])throw new ServiceIssue('APPLICATION_CHANGED','The application changed elsewhere. Reload before continuing.',409);return rows[0];}
export async function candidateAction(person:Person,id:string,version:number,status:'accepted'|'declined'|'withdrawn'){
 const [current]=await query<Application>('SELECT * FROM hub_job_applications WHERE id=$1 AND scope=$2 AND person_id=$3',[id,person.scope,person.id]);if(!current)throw new ServiceIssue('APPLICATION_NOT_FOUND','This application is not available to you.',404);
 if(!validTransition(current.status,status,'employment'))throw new ServiceIssue('APPLICATION_TRANSITION_INVALID','This response is not available now. Reload the application.',409);
 return change(person,current,status,status==='accepted'?'Candidate accepted the offer; appointment remains subject to onboarding and approvals.':status==='declined'?'Candidate declined the offer.':'Candidate withdrew the application.',version);
}
