import { redirect,notFound } from "next/navigation";

import { modules,can,type Person } from "@/lib/contracts";
import { currentPerson } from "@/lib/session";
import { overview } from "@/lib/data";
import { ServiceIssue } from "@/lib/db";
import { WorkspaceShell } from "@/components/WorkspaceShell";
import { BoardView,ExecutiveView,Hero,Panel,Empty,Documents } from "@/components/BoardView";
import { InvestorView } from "@/components/InvestorView";
import { Recovery } from "@/components/Recovery";
import { ProfileForm } from "@/components/ProfileForm";
import { DocumentForm } from "@/components/DocumentForm";
import { ActionButton } from "@/components/ActionButton";
import { Icon } from "@/components/Icon";
export const dynamic='force-dynamic';
export default async function Module({params,searchParams}:{params:Promise<{module:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {module}=await params;const item=modules.find(item=>item.id===module);if(!item)notFound();
 let person:Person|null;try{person=await currentPerson();}catch(error){if(error instanceof ServiceIssue)return <Recovery message={error.message} code={error.code}/>;throw error;}
 if(!person)redirect(`/login?next=${encodeURIComponent('/'+module)}`);
 if(!['profile','settings'].includes(module)&&!can(person.roles,item.roles))return <WorkspaceShell person={person} active={module}><Recovery title="This workspace is not available to your account" message="Your current Citizen roles do not permit this area. Go back or open a permitted workspace." code="WORKSPACE_ACCESS_DENIED"/></WorkspaceShell>;
 if(item.comingSoon)return <WorkspaceShell person={person} active={module}><Hero title={item.label} subtitle={item.description}/><section className={`coming-soon ${module==='ai'?'immersive-ai':''}`}><div className="brand-orb"/><span className="chip purple">Coming soon</span><h2>{module==='ai'?'Meet Citizen AI':`${item.label}, connected to your institution`}</h2><p>{module==='ai'?'Permission-aware assistance, grounded answers and an immersive voice experience. This integration is being prepared.':item.description+' The complete workflow will appear here once its integration has been verified.'}</p><a className="button primary" href="/">Return to your workspace</a></section></WorkspaceShell>;
 const search=await searchParams;
 let data;try{data=await overview(person);}catch(error){if(error instanceof ServiceIssue)return <WorkspaceShell person={person} active={module}><Recovery title="Institutional data is temporarily unavailable" message={error.message} code={error.code}/></WorkspaceShell>;throw error;}
 return <WorkspaceShell person={person} active={module}>
 {module==='board'&&<BoardView person={person} data={data}/>}
 {module==='executive'&&<ExecutiveView person={person} data={data}/>}
 {module==='investors'&&<InvestorView person={person} data={data}/>}
 {module==='documents'&&<><Hero title="Documents & Knowledge" subtitle="Your institution’s knowledge. Securely connected." description="Files stay in Google Drive. Citizen keeps shared links and access metadata."/>
 <div className="dashboard-layout"><div className="primary-column"><div className="document-toolbar"><form><Icon name="search"/><input name="q" defaultValue={search.q||''} placeholder="Search your documents" aria-label="Search your documents"/><button className="button" type="submit">Search</button></form><a className="button primary" href="/documents?link=1">+ Link document</a></div>{search.link==='1'?<DocumentForm/>:<Panel title="Your documents"><Documents data={{...data,documents:search.q?data.documents.filter(doc=>(doc.name+' '+doc.category).toLowerCase().includes(search.q!.toLowerCase())):data.documents}}/></Panel>}</div><aside className="context-column"><Panel title="Google Drive, by design"><p className="muted">Your document remains in Google Drive. Its existing Drive permissions continue to apply when you open it.</p><p className="muted">Citizen stores a file identifier, shared link, category and permission metadata. It stores no document bytes.</p></Panel><Panel title="Upload integration"><span className="chip purple">Coming soon</span><p className="muted">Direct upload and automatic Drive filing will be available after the authorised Drive connection is configured.</p></Panel></aside></div></>}
 {module==='profile'&&<><Hero title="Your Citizen Profile" subtitle="One identity. Every role connected."/><div className="dashboard-layout"><div className="primary-column">{search.edit==='1'?<ProfileForm person={person}/>:<Panel title="Personal information"><dl className="profile-details">{[['Name',person.display_name],['Email',person.email],['Contact number',person.phone||'Not provided'],['Country',person.country||'Not provided'],['Occupation',person.occupation||'Not provided'],['About you',person.bio||'Not provided']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><a className="button primary" href="/profile?edit=1">Update your profile</a></Panel>}</div><aside className="context-column"><Panel title="Your roles"><div className="role-list">{person.roles.map(role=><span className="chip" key={role}>{role.replaceAll('_',' ')}</span>)}</div><p className="muted">Roles control your permitted workspaces. They cannot be changed through your personal profile.</p></Panel>{person.roles.includes('customer')&&<Panel title="Customer profile"><p className="muted">Manage banking-specific information within Internet Banking or the app.</p><a className="button" href="/api/platform/handoff?audience=banking">Open Internet Banking</a></Panel>}</aside></div></>}
 {module==='communications'&&<><Hero title="Communications" subtitle="Your institutional conversations and updates."/><div className="dashboard-layout"><div className="primary-column"><Panel title="Your notifications">{data.notifications.length?data.notifications.map(notification=><article className="notification-row" key={notification.id}><span className={`tone-icon tone-${notification.read_at?'2':'0'}`}><Icon name="communications"/></span><div><h3>{notification.title}</h3><p>{notification.body}</p><a href={notification.path}>Open workspace ↗</a></div>{!notification.read_at&&<ActionButton label="Mark read" path="/api/workspace" payload={{action:'read_notification',id:notification.id}}/>}</article>):<Empty>You have no notifications yet.</Empty>}</Panel></div><aside className="context-column"><Panel title="Secure discussions"><span className="chip purple">Coming soon</span><p className="muted">Channels, direct discussions and permissioned attachments will join this workspace as their integrations are completed.</p></Panel></aside></div></>}
 {module==='settings'&&<><Hero title="Workspace Settings" subtitle="Your preferences. Your security. Your connected services."/><div className="settings-grid"><Panel title="Account and identity"><p>{person.email}</p><p className="muted">Authentication is verified on the server. Citizen Hub uses an HTTP-only, revocable session.</p><a className="button" href="/profile">Manage profile</a></Panel><Panel title="Connected services"><a className="button" href={process.env.NEXT_PUBLIC_WEBSITE_URL}>Citizen Bank website ↗</a>{person.roles.includes('customer')&&<><a className="button" href="/api/platform/handoff?audience=banking">Internet Banking ↗</a><a className="button" href="/api/platform/handoff?audience=app">Citizen Bank App ↗</a></>}</Panel><Panel title="Notifications"><a className="button" href="/communications">View institutional updates</a><p className="muted">Email, messaging and channel preference integration is coming soon.</p></Panel><Panel title="Organisation and integrations"><p className="muted">Google Drive upload, delegated approvals and administration tools are coming soon. Current documents use existing permissioned Drive shared links.</p></Panel></div></>}
 </WorkspaceShell>;
}
