import {currentPerson} from '@/lib/session';
import {opportunities} from '@/lib/investments';
import {can} from '@/lib/contracts';
import {WorkspaceShell} from '@/components/WorkspaceShell';
import {Hero,Panel,Empty} from '@/components/BoardView';
import {SubscriptionForm} from '@/components/SubscriptionForm';
import {SubscriptionReview} from '@/components/SubscriptionReview';
import {Recovery} from '@/components/Recovery';
import {ServiceIssue} from '@/lib/db';
import {money} from '@/lib/data';
export const dynamic='force-dynamic';
export default async function Opportunities({searchParams}:{searchParams:Promise<{subscribe?:string}>}){
 try{
 const person=await currentPerson(),{subscribe}=await searchParams,data=await opportunities(person),offer=data.offers.find(o=>o.id===subscribe),admin=!!person&&can(person.roles,['admin']);
 const content=<><Hero title="Invest in Citizen’s future" subtitle="SAFE subscriptions and your investment journey." kind="investor" description="Review the evidence, request your subscription and track its review. A SAFE represents conditional future equity; shares are issued only after conversion."/>
 <div className="dashboard-layout"><div className="primary-column">{offer&&person?<Panel title={offer.title}><SubscriptionForm offer={offer} person={person}/></Panel>:<Panel title="Available opportunities">{subscribe&&!offer&&<p role="status">That opportunity has changed or closed. Choose an available opportunity below.</p>}<div className="opportunity-grid">{data.offers.map(o=><article className="opportunity-card" key={o.id}><span className="chip">{o.instrument}</span><h2>{o.title}</h2><p>{o.summary}</p><p>{money(o.unit_price,o.currency)} per reference share · minimum {o.min_units.toLocaleString()} · {money(Number(o.unit_price)*o.min_units,o.currency)}</p>{o.terms_link&&<a href={o.terms_link} target="_blank" rel="noopener noreferrer">Review the SAFE template in Google Drive ↗</a>}<a className="button primary" href={person?'/opportunities?subscribe='+o.id:'/login?next='+encodeURIComponent('/opportunities?subscribe='+o.id)}>Request a subscription</a></article>)}</div>{!data.offers.length&&<Empty>Subscription publication is being prepared. Review the data room or contact investor support for current terms.</Empty>}</Panel>}
 <Panel title={admin?'Subscription review queue':'Your subscription requests'}>{data.requests.length?<div className="readiness-items">{data.requests.map(r=><article className="finding-row" key={r.id}><h3>{r.title}</h3>{admin&&<p>{r.display_name} · {r.email}</p>}<p>{r.units.toLocaleString()} reference shares · {money(Number(r.unit_price)*r.units,r.currency)} · <span className="chip">{r.status.replaceAll('_',' ')}</span></p><small>Request reference {r.id}</small>{r.review_note&&<p>{r.review_note}</p>}<div className="actions">{r.agreement_link&&<a className="button" href={r.agreement_link} target="_blank" rel="noopener noreferrer">Signed SAFE agreement ↗</a>}{r.payment_link&&<a className="button" href={r.payment_link} target="_blank" rel="noopener noreferrer">Payment evidence ↗</a>}<a className="button" href={'/subscriptions/'+r.id}>View subscription &amp; document previews</a></div>{admin&&<SubscriptionReview id={r.id} version={r.version} status={r.status} agreement={r.agreement_link} payment={r.payment_link}/>}</article>)}</div>:<Empty>No subscription requests recorded.</Empty>}</Panel></div>
 <aside className="context-column"><Panel title="Make an informed decision"><p>Review company information and evidence before requesting a subscription.</p><a className="button primary" href="/dataroom">Open investor data room</a><p className="muted">Licence approval, investment returns and conversion are not guaranteed. Your capital is at risk.</p></Panel><Panel title="One Citizen profile"><p>{person?person.display_name:'Use your existing Citizen account, or register as a new investor.'}</p>{person?<a className="button" href="/profile">Manage my profile</a>:<><a className="button" href="/register">Create investor account</a><a className="button" href="/login?next=/opportunities">Sign in</a></>}<p className="muted">A request does not transfer money, allot shares or grant administrative access.</p><a href="mailto:investors@citizenbank.co.ls">Contact investor support</a></Panel></aside></div></>;
 return person?<WorkspaceShell person={person} active="investors">{content}</WorkspaceShell>:<main className="public-opportunities" id="main"><a className="button" href={process.env.NEXT_PUBLIC_WEBSITE_URL}>← Citizen Bank website</a>{content}</main>;
 }catch(e){if(e instanceof ServiceIssue)return <Recovery code={e.code} message={e.message}/>;throw e;}}
